name: build-dexkit-helper

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: 8.2.1

      - name: Build debug
        run: gradle :app:assembleDebug

      - name: Find classes.jar
        run: |
          JAR_PATH=$(find app/build -name "classes.jar" | head -n 1)
          echo "JAR_PATH=$JAR_PATH" >> $GITHUB_ENV
          echo "Found classes.jar: $JAR_PATH"

      - name: D8 to dex
        run: |
          $ANDROID_HOME/build-tools/34.0.0/d8 "$JAR_PATH" --output outDex

      - name: Rename
        run: cp outDex/classes.dex dexkit-helper.dex

      - uses: actions/upload-artifact@v4
        with:
          name: dexkit-helper
          path: dexkit-helper.dex